zuul:
  #Service will be mapped under the /api URI
  prefix: /api
#  Uncomment to disable auto-registering all services read from Eureka
#  ignoredServices: '*'
  routes:
    identity-service:
      path: /identity/**
      serviceId: chili-identity-service
    static:
      path: /static/**
      
spring:
  application:
     name: chili-api-gateway  # Service registers under this name
