FROM java:8
VOLUME /tmp
ADD chili-config-server-1.0-SNAPSHOT.jar chili-config-server.jar
RUN sh -c 'touch /chili-config-server.jar'
ENV JAVA_OPTS=""
ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /chili-config-server.jar" ]
