package office_mda.compiled;

import org.eclipse.jet.JET2Context;
import org.eclipse.jet.JET2Template;
import org.eclipse.jet.JET2Writer;

public class _jet_projectproperties implements JET2Template {

    public _jet_projectproperties() {
        super();
    }

    private static final String NL = System.getProperty("line.separator"); //$NON-NLS-1$

    public void generate(final JET2Context context, final JET2Writer __out) {
        JET2Writer out = __out;
        out.write("# This file is automatically generated by Android Tools.");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("# Do not modify this file -- YOUR CHANGES WILL BE ERASED!");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("#");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("# This file must be checked in Version Control Systems.");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("#");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("# To customize properties used by the Ant build system use,");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("# \"ant.properties\", and override values to adapt the script to your");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("# project structure.");  //$NON-NLS-1$        
        out.write(NL);         
        out.write(NL);         
        out.write("# Project target.");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("target=android-8");  //$NON-NLS-1$        
        out.write(NL);         
    }
}
