spring:
  application:
    name: chili-config-client
  cloud:
    config:
      name: configuration
      env: default # optional
      label: master # optional
      uri: http://localhost:4444 # optional
# HTTP Server
server:
  port: 5555   # HTTP (Tomcat) port
