--
-- System Soft Technologies Copyright (C) 2013 ayalamanchili@sstech.mobi
--


 create table AdvanceRequisition (
        id bigint generated by default as identity (start with 1),
        version integer,
        amount numeric,
        approvedBy varchar(255),
        approvedDate date,
        bpmProcessId varchar(255),
        dateRequested date,
        neededBy date,
        notes longvarchar,
        payrollFileNumber varchar(255),
        purpose longvarchar,
        status varchar(255),
        employee_id bigint,
        primary key (id)
    )ENGINE=InnoDB DEFAULT CHARSET=utf8;
create table AdvanceRequisition_aud (
        id bigint generated by default as identity (start with 1),
        version integer,
        amount numeric,
        approvedBy varchar(255),
        approvedDate date,
        bpmProcessId varchar(255),
        dateRequested date,
        neededBy date,
        notes longvarchar,
        payrollFileNumber varchar(255),
        purpose longvarchar,
        status varchar(255),
        employee_id bigint,
        primary key (id)
    )ENGINE=InnoDB DEFAULT CHARSET=utf8;
