--
-- System Soft Technologies Copyright (C) 2013 ayalamanchili@sstech.mobi
--
CREATE TABLE `TravelAuthorization` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `version` int(11) DEFAULT NULL,
  `bpmProcessId` varchar(255) DEFAULT NULL,
  `ceoApprovalBy` varchar(255) DEFAULT NULL,
  `ceoApprovalDate` date DEFAULT NULL,
  `dateRequested` date DEFAULT NULL,
  `department` varchar(255) DEFAULT NULL,
  `departureDate` date NOT NULL,
  `manaerApprovalDate` date DEFAULT NULL,
  `managerApprovalBy` varchar(255) DEFAULT NULL,
  `phoneNumber` varchar(255) DEFAULT NULL,
  `reasonForTravel` longtext NOT NULL,
  `returnDate` date NOT NULL,
  `status` varchar(255) DEFAULT NULL,
  `totalEstimatedTripExpences` decimal(19,2) DEFAULT NULL,
  `expenseAccommodationPaymentType` varchar(255) DEFAULT NULL,
  `lodgingCostPerNight` decimal(19,2) DEFAULT NULL,
  `numberOfLodgingNights` decimal(19,2) DEFAULT NULL,
  `totalLodgingCost` decimal(19,2) DEFAULT NULL,
  `travelDestination` varchar(255) NOT NULL,
  `banquetExpensePaymentMode` varchar(255) DEFAULT NULL,
  `conferenceExpensePaymentMode` varchar(255) DEFAULT NULL,
  `conferenceFee` decimal(19,2) DEFAULT NULL,
  `foodExpensePaymentMode` varchar(255) DEFAULT NULL,
  `otherExpences` decimal(19,2) DEFAULT NULL,
  `otherExpensePaymentMode` varchar(255) DEFAULT NULL,
  `totalCostOfBanquet` decimal(19,2) DEFAULT NULL,
  `totalCostOfFood` decimal(19,2) DEFAULT NULL,
  `costPerMile` decimal(19,2) DEFAULT NULL,
  `expensePaymentType` varchar(255) DEFAULT NULL,
  `totalMiles` decimal(19,2) DEFAULT NULL,
  `totalTransportationCost` decimal(19,2) DEFAULT NULL,
  `estimatedCostOfOtherTransportation` decimal(19,2) DEFAULT NULL,
  `expenseRentalPaymentType` varchar(255) DEFAULT NULL,
  `otherVehicleTypeJustification` longtext,
  `rentalVehicleJustification` longtext,
  `travelRentalVehicleType` varchar(255) DEFAULT NULL,
  `travelTransportationType` varchar(255) DEFAULT NULL,
  `travelType` varchar(255) NOT NULL,
  `employee_id` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `TRVL_AUTH_DT_REQ_IDX` (`dateRequested`),
  KEY `FK_Emp_TravelAuths` (`employee_id`),
  CONSTRAINT `FK_Emp_TravelAuths` FOREIGN KEY (`employee_id`) REFERENCES `Contact` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `TravelAuthorization_AUD` (
  `id` bigint(20) NOT NULL,
  `REV` bigint(20) NOT NULL,
  `REVTYPE` tinyint(4) DEFAULT NULL,
  `bpmProcessId` varchar(255) DEFAULT NULL,
  `ceoApprovalBy` varchar(255) DEFAULT NULL,
  `ceoApprovalDate` date DEFAULT NULL,
  `dateRequested` date DEFAULT NULL,
  `department` varchar(255) DEFAULT NULL,
  `departureDate` date DEFAULT NULL,
  `manaerApprovalDate` date DEFAULT NULL,
  `managerApprovalBy` varchar(255) DEFAULT NULL,
  `phoneNumber` varchar(255) DEFAULT NULL,
  `reasonForTravel` longtext,
  `returnDate` date DEFAULT NULL,
  `status` varchar(255) DEFAULT NULL,
  `totalEstimatedTripExpences` decimal(19,2) DEFAULT NULL,
  `expenseAccommodationPaymentType` varchar(255) DEFAULT NULL,
  `lodgingCostPerNight` decimal(19,2) DEFAULT NULL,
  `numberOfLodgingNights` decimal(19,2) DEFAULT NULL,
  `totalLodgingCost` decimal(19,2) DEFAULT NULL,
  `travelDestination` varchar(255) DEFAULT NULL,
  `banquetExpensePaymentMode` varchar(255) DEFAULT NULL,
  `conferenceExpensePaymentMode` varchar(255) DEFAULT NULL,
  `conferenceFee` decimal(19,2) DEFAULT NULL,
  `foodExpensePaymentMode` varchar(255) DEFAULT NULL,
  `otherExpences` decimal(19,2) DEFAULT NULL,
  `otherExpensePaymentMode` varchar(255) DEFAULT NULL,
  `totalCostOfBanquet` decimal(19,2) DEFAULT NULL,
  `totalCostOfFood` decimal(19,2) DEFAULT NULL,
  `costPerMile` decimal(19,2) DEFAULT NULL,
  `expensePaymentType` varchar(255) DEFAULT NULL,
  `totalMiles` decimal(19,2) DEFAULT NULL,
  `totalTransportationCost` decimal(19,2) DEFAULT NULL,
  `estimatedCostOfOtherTransportation` decimal(19,2) DEFAULT NULL,
  `expenseRentalPaymentType` varchar(255) DEFAULT NULL,
  `otherVehicleTypeJustification` longtext,
  `rentalVehicleJustification` longtext,
  `travelRentalVehicleType` varchar(255) DEFAULT NULL,
  `travelTransportationType` varchar(255) DEFAULT NULL,
  `travelType` varchar(255) DEFAULT NULL,
  `employee_id` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id`,`REV`),
  KEY `FKF33899B05B7A65D0` (`REV`),
  CONSTRAINT `FKF33899B05B7A65D0` FOREIGN KEY (`REV`) REFERENCES `AuditRevisionEntity` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

