DROP TABLE IF EXISTS `lca`;

CREATE TABLE `lca` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `version` int(11) DEFAULT NULL,
  `candidateNames` varchar(255) DEFAULT NULL,
  `certifiedLcaSentConsultant` date DEFAULT NULL,
  `clientName` varchar(255) DEFAULT NULL,
  `comment` varchar(255) DEFAULT NULL,
  `jobTitle` varchar(255) NOT NULL,
  `lcaCurrMaxWage` decimal(19,2) DEFAULT NULL,
  `lcaCurrMinWage` decimal(19,2) NOT NULL,
  `lcaCurrWageLvl` varchar(255) NOT NULL,
  `lcaFiledDate` date DEFAULT NULL,
  `lcaFiledInPIF` date DEFAULT NULL,
  `lcaNumber` varchar(255) NOT NULL,
  `lcaPostingSSTLocation` date DEFAULT NULL,
  `lcaPostingSentToVendor` date DEFAULT NULL,
  `lcaValidFromDate` date NOT NULL,
  `lcaValidToDate` date NOT NULL,
  `nonDisplacement` varchar(255) DEFAULT NULL,
  `reminderEmail` date DEFAULT NULL,
  `responseOnLcaPosting` date DEFAULT NULL,
  `socCodesAndOccupations` varchar(255) DEFAULT NULL,
  `status` varchar(255) DEFAULT NULL,
  `totalPendingPositions` bigint(20) DEFAULT NULL,
  `totalWorkingPositions` bigint(20) DEFAULT NULL,
  `vendorName` varchar(255) DEFAULT NULL,
  `visaClassification` varchar(255) NOT NULL,
  `withdrawnLCANumber` varchar(255) DEFAULT NULL,
  `company_id` bigint(20) DEFAULT NULL,
  `employee_id` bigint(20) DEFAULT NULL,
  `lcaAddress1_id` bigint(20) DEFAULT NULL,
  `lcaAddress2_id` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `LCA_VALID_FROM_DATE` (`lcaValidFromDate`),
  KEY `LCA_NBR` (`lcaNumber`),
  KEY `LCA_VALID_TO_DATE` (`lcaValidToDate`),
  KEY `FK_LCA_Company` (`company_id`),
  KEY `FK125AADDFC507E` (`lcaAddress2_id`),
  KEY `FK_Emp_Lca` (`employee_id`),
  KEY `FK125AADDFBDC1F` (`lcaAddress1_id`),
  CONSTRAINT `FK125AADDFBDC1F` FOREIGN KEY (`lcaAddress1_id`) REFERENCES `address` (`id`),
  CONSTRAINT `FK125AADDFC507E` FOREIGN KEY (`lcaAddress2_id`) REFERENCES `address` (`id`),
  CONSTRAINT `FK_Emp_Lca` FOREIGN KEY (`employee_id`) REFERENCES `contact` (`id`),
  CONSTRAINT `FK_LCA_Company` FOREIGN KEY (`company_id`) REFERENCES `company` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `lca_aud`;

CREATE TABLE `lca_aud` (
  `id` bigint(20) NOT NULL,
  `REV` bigint(20) NOT NULL,
  `REVTYPE` tinyint(4) DEFAULT NULL,
  `candidateNames` varchar(255) DEFAULT NULL,
  `certifiedLcaSentConsultant` date DEFAULT NULL,
  `clientName` varchar(255) DEFAULT NULL,
  `comment` varchar(255) DEFAULT NULL,
  `jobTitle` varchar(255) DEFAULT NULL,
  `lcaCurrMaxWage` decimal(19,2) DEFAULT NULL,
  `lcaCurrMinWage` decimal(19,2) DEFAULT NULL,
  `lcaCurrWageLvl` varchar(255) DEFAULT NULL,
  `lcaFiledDate` date DEFAULT NULL,
  `lcaFiledInPIF` date DEFAULT NULL,
  `lcaNumber` varchar(255) DEFAULT NULL,
  `lcaPostingSSTLocation` date DEFAULT NULL,
  `lcaPostingSentToVendor` date DEFAULT NULL,
  `lcaValidFromDate` date DEFAULT NULL,
  `lcaValidToDate` date DEFAULT NULL,
  `nonDisplacement` varchar(255) DEFAULT NULL,
  `reminderEmail` date DEFAULT NULL,
  `responseOnLcaPosting` date DEFAULT NULL,
  `socCodesAndOccupations` varchar(255) DEFAULT NULL,
  `status` varchar(255) DEFAULT NULL,
  `totalPendingPositions` bigint(20) DEFAULT NULL,
  `totalWorkingPositions` bigint(20) DEFAULT NULL,
  `vendorName` varchar(255) DEFAULT NULL,
  `visaClassification` varchar(255) DEFAULT NULL,
  `withdrawnLCANumber` varchar(255) DEFAULT NULL,
  `company_id` bigint(20) DEFAULT NULL,
  `employee_id` bigint(20) DEFAULT NULL,
  `lcaAddress1_id` bigint(20) DEFAULT NULL,
  `lcaAddress2_id` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id`,`REV`),
  KEY `FK2A6E6E7B5B7A65D0` (`REV`),
  CONSTRAINT `FK2A6E6E7B5B7A65D0` FOREIGN KEY (`REV`) REFERENCES `auditrevisionentity` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
